---
title: "Basic Analysis of the Congressional Record and Hansard"
output: pdf_document
fontsize: 12pt
---

# Setup
```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(quanteda)
library(quanteda.dictionaries)

data_dir <- "analysis/data"
dist_dir <- "analysis/dist"

congressional_record_path <-
    "congressional-record/dist/congressional_record.csv"
hansard_path <- "hansard-in-full/hansard_in_full.csv"
```

# Congressional Record and Hansard document-feature matrix

## Congressional Record

### Loading the Congressional Record as a corpus
```{r congressional_record}
congressional_record <- read_csv(congressional_record_path)

# Filterting to only the 114th Congress to speed up priliminary analysis
congressional_record_filtered <- congressional_record |>
    filter(congress == "111")

congressional_record_corpus <-
    corpus(congressional_record_filtered, text_field = "speech")
```

### Creating the Congressional Record document-feature matrix
```{r congressional_record_dfm}
congressional_record_dfm <- congressional_record_corpus |>
    tokens(remove_punct = TRUE) |>
    dfm() |>
    dfm_remove(pattern = stopwords("en")) |>
    dfm_trim(min_termfreq = 5)
```

# Climate term filtering

## Creating a climate term dictionary
```{r climate_dictionary}
basic_climate_dictionary <-
    read_csv(paste0(data_dir, "/basic_climate_change_dictionary.csv"))

climate_dictionary_list <- list(
    word = basic_climate_dictionary$word
)

climate_dictionary <- dictionary(climate_dictionary_list)
```

## Applying the climate term dictionary to the Congressional Record
```{r congressional_record_climate_dfm}
congressional_record_climate_dictionary <- dfm_lookup(
    congressional_record_dfm,
    dictionary = climate_dictionary
)

congressional_record_nwords <- ntoken(congressional_record_corpus)
congressional_record_dictionary_proportions <-
    congressional_record_climate_dictionary / congressional_record_nwords

congressional_record_filtered$climate_proportion <- as.numeric(
    congressional_record_dictionary_proportions
)
```

```{r congressional_record_climate_proportion}
highest_climate_texts <- congressional_record_filtered |>
    arrange(desc(climate_proportion)) |>
    head(100)

write_csv(highest_climate_texts, paste0(dist_dir, "/highest_climate_texts.csv"))
```
